[package]
name = "aoc2024"
version = "0.1.0"
edition = "2021"

[[bin]]
name="d01"
path = "day-01/main.rs"

[[bin]]
name="d02"
path = "day-02/main.rs"

[[bin]]
name="d03"
path = "day-03/main.rs"

[dependencies]
regex = "1.11.1"
