[package]
name = "aoc2024"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "d01"
path = "day_01/main.rs"

[[bin]]
name = "d02"
path = "day_02/main.rs"

[[bin]]
name = "d03"
path = "day_03/main.rs"

[[bin]]
name = "d04"
path = "day_04/main.rs"

[dependencies]
regex = "1.11.1"
